### ISSUE TITLE
Jest test output has unnecessary extra logging 

### ISSUE THREAD

**Issue by kj800x** [kj800x/react-observable-connect#4]
The Jest output has a lot of extra logging because some of our tests intentionally test the error cases (where the function throws an error). Although we catch these in the tests, the stacktraces are still getting dumped. Although this is not critical, it's unsightly and misleading, as the developer gets messages that look like errors when all the tests pass.

It appears that these errors are potentially related to JSDOM.

Example output snippet from a successful run of the tests:
```
Error: Uncaught [TypeError: objToFuncProps is not a function]
    at reportException (/home/kevin/Desktop/react-observable-connect/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/home/kevin/Desktop/react-observable-connect/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at HTMLUnknownElementImpl._dispatch (/home/kevin/Desktop/react-observable-connect/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (/home/kevin/Desktop/react-observable-connect/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (/home/kevin/Desktop/react-observable-connect/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    ...
```

**Comment by kj800x** [comment]
Although the commit appeared to have fixed it (based on the travis log) and I remember it working, this bug has regressed and when I checkout 94e467c it still exists. Reopening this for now.
